// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lighthouse_construction_progress_api.Infrastructure.Persistence;

#nullable disable

namespace lighthouse_construction_progress_api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211125132540_Indexes")]
    partial class Indexes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("lighthouse_construction_progress_api.Domain.Entities.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Acs")
                        .HasColumnType("datetime2");

                    b.Property<string>("ActivityNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("BasePlannedProgress")
                        .HasColumnType("float");

                    b.Property<DateTime?>("Bef")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Bes")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Besa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Cancelled")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Csh")
                        .HasColumnType("float");

                    b.Property<DateTime?>("CurrentAf")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CurrentAs")
                        .HasColumnType("datetime2");

                    b.Property<double?>("CurrentPlannedProgress")
                        .HasColumnType("float");

                    b.Property<double?>("CurrentProgress")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Du")
                        .HasColumnType("float");

                    b.Property<DateTime?>("Ef")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Es")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Esa")
                        .HasColumnType("datetime2");

                    b.Property<double?>("ExpendedQuantity")
                        .HasColumnType("float");

                    b.Property<string>("F10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("JobPackEstimatedQuantity")
                        .HasColumnType("float");

                    b.Property<DateTime?>("Lf")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Ls")
                        .HasColumnType("datetime2");

                    b.Property<long>("NetId")
                        .HasColumnType("bigint");

                    b.Property<double?>("OnTarget")
                        .HasColumnType("float");

                    b.Property<string>("R10Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R10SubDiscipline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R11Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R11Responsible")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R12Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R12ProjectMilestone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R13ActivityRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R13Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R14Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R14ProjectPhase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R15Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R15Fav")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R16Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R16Fas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R17Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R17Pau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R18Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R18Module")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R19Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R19SapWbs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R1Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R1Wbs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R20Contract")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R20Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R21Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R21SubSystem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R22Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R22MaterialAllocationPhase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R23ContractorCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R23Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R24CostCenterDepartment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R24Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R25Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R25McPk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R26Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R26TagTest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R27Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R27SiteLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R28Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R28WorkType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R29Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R29JobDisc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R2Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R2MainCat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R30Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R30PersonalSortField")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R3Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R3Discipline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R4Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R4MainArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R5Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R5SubArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R6Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R6System")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R7CommPk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R7Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R8Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R8ProcurementPack")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R9Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("R9Phase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Rsh")
                        .HasColumnType("float");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Tse")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("lighthouse_construction_progress_api.Domain.Entities.LciObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActivityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActivityNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cable_F_Area")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cable_F_Tag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cable_T_Area")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cable_T_Tag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComPkg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("EstimatedQuantity")
                        .HasColumnType("float");

                    b.Property<double?>("InstalledQuantity")
                        .HasColumnType("float");

                    b.Property<string>("McPkg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PipeTest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("RemainingHours")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StatusDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StatusName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkOrderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkOrderNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkTypeNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("LciObjects");
                });

            modelBuilder.Entity("lighthouse_construction_progress_api.Domain.Entities.WorkOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActivityNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EstimatedEndTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("EstimatedHours")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("EstimatedStartTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("HoursUsed")
                        .HasColumnType("float");

                    b.Property<int>("Progress")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StatusDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("WoNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("WorkOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
