namespace lighthouse_construction_progress_api.Domain.Entities;

public class Activity
{
    public long Id { get; set; }
    public string? ActivityNo { get; set; }
    public string? Description { get; set; }
    public long Sequence { get; set; }
    public long NetId { get; set; }
    public string? F10 { get; set; }
    public string? R1Wbs { get; set; }
    public string? R1Description { get; set; }
    public string? R2MainCat { get; set; }
    public string? R2Description { get; set; }
    public string? R3Discipline { get; set; }
    public string? R3Description { get; set; }
    public string? R4MainArea { get; set; }
    public string? R4Description { get; set; }
    public string? R5SubArea { get; set; }
    public string? R5Description { get; set; }
    public string? R6System { get; set; }
    public string? R6Description { get; set; }
    public string? R7CommPk { get; set; }
    public string? R7Description { get; set; }
    public string? R8ProcurementPack { get; set; }
    public string? R8Description { get; set; }
    public string? R9Phase { get; set; }
    public string? R9Description { get; set; }
    public string? R10SubDiscipline { get; set; }
    public string? R10Description { get; set; }
    public string? R11Responsible { get; set; }
    public string? R11Description { get; set; }
    public string? R12ProjectMilestone { get; set; }
    public string? R12Description { get; set; }
    public string? R13ActivityRole { get; set; }
    public string? R13Description { get; set; }
    public string? R14ProjectPhase { get; set; }
    public string? R14Description { get; set; }
    public string? R15Fav { get; set; }
    public string? R15Description { get; set; }
    public string? R16Fas { get; set; }
    public string? R16Description { get; set; }
    public string? R17Pau { get; set; }
    public string? R17Description { get; set; }
    public string? R18Module { get; set; }
    public string? R18Description { get; set; }
    public string? R19SapWbs { get; set; }
    public string? R19Description { get; set; }
    public string? R20Contract { get; set; }
    public string? R20Description { get; set; }
    public string? R21SubSystem { get; set; }
    public string? R21Description { get; set; }
    public string? R22MaterialAllocationPhase { get; set; }
    public string? R22Description { get; set; }
    public string? R23ContractorCode { get; set; }
    public string? R23Description { get; set; }
    public string? R24CostCenterDepartment { get; set; }
    public string? R24Description { get; set; }
    public string? R25McPk { get; set; }
    public string? R25Description { get; set; }
    public string? R26TagTest { get; set; }
    public string? R26Description { get; set; }
    public string? R27SiteLocation { get; set; }
    public string? R27Description { get; set; }
    public string? R28WorkType { get; set; }
    public string? R28Description { get; set; }
    public string? R29JobDisc { get; set; }
    public string? R29Description { get; set; }
    public string? R30PersonalSortField { get; set; }
    public string? R30Description { get; set; }
    public string? Du { get; set; }
    public string? Tse { get; set; }
    public string? Acs { get; set; }
    public string? Es { get; set; }
    public string? Ef { get; set; }
    public string? Ls { get; set; }
    public string? Lf { get; set; }
    public string? OnTarget { get; set; }
    public string? CurrentProgress { get; set; }
    public string? Cancelled { get; set; }
    public string? JobPackEstimatedQuantity { get; set; }
    public string? ExpendedQuantity { get; set; }
    public string? Esa { get; set; }
    public string? CurrentAs { get; set; }
    public string? CurrentAf { get; set; }
    public string? CurrentPlannedProgress { get; set; }
    public string? BasePlannedProgress { get; set; }
    public string? Bes { get; set; }
    public string? Besa { get; set; }
    public string? Bef { get; set; }
    public string? Rsh { get; set; }
    public string? Csh { get; set; }
}